-- ============================================================
-- Customer Shopping Behavior Analysis -- SQL Queries (MySQL)
-- Table: customer_final_data
-- ============================================================

USE customer_behavior;

-- ------------------------------------------------------------
-- CORE BUSINESS QUESTIONS
-- ------------------------------------------------------------

-- Q1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount_usd) AS revenue
FROM customer_final_data
GROUP BY gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount_usd
FROM customer_final_data
WHERE discount_applied = 'Yes'
  AND purchase_amount_usd >= (SELECT AVG(purchase_amount_usd) FROM customer_final_data);


-- Q3. Which are the top 5 products with the highest average review rating?
-- FIX: removed PostgreSQL-only "::numeric" cast syntax, which is invalid in MySQL.
-- review_rating is already numeric, so no cast is needed at all.
SELECT item_purchased,
       ROUND(AVG(review_rating), 2) AS avg_product_rating
FROM customer_final_data
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT shipping_type,
       ROUND(AVG(purchase_amount_usd), 2) AS avg_purchase_amount
FROM customer_final_data
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue
-- between subscribers and non-subscribers.
-- FIX: original ORDER BY total_revenue, avg_spend DESC only sorted avg_spend descending;
-- total_revenue was sorting ascending by default. Made intent explicit below.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount_usd), 2) AS avg_spend,
       ROUND(SUM(purchase_amount_usd), 2) AS total_revenue
FROM customer_final_data
GROUP BY subscription_status
ORDER BY total_revenue DESC;


-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer_final_data
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on their total
-- number of previous purchases, and show the count of each segment.
WITH customer_type AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer_final_data
)
SELECT customer_segment, COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;


-- Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_final_data
    GROUP BY category, item_purchased
)
SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_final_data
WHERE previous_purchases > 5
GROUP BY subscription_status;


-- Q10. What is the revenue contribution of each age group?
SELECT age_group,
       SUM(purchase_amount_usd) AS total_revenue
FROM customer_final_data
GROUP BY age_group
ORDER BY total_revenue DESC;


-- ------------------------------------------------------------
-- INDUSTRY-LEVEL QUESTIONS
-- ------------------------------------------------------------

-- Q11. Who are the top 10 customers by lifetime spend (Customer Lifetime Value proxy)?
-- Useful for VIP/high-value customer targeting in a retention or loyalty campaign.
SELECT customer_id,
       purchase_amount_usd,
       RANK() OVER (ORDER BY purchase_amount_usd DESC) AS spend_rank
FROM customer_final_data
ORDER BY spend_rank
LIMIT 10;


-- Q12. How do customers score on an RFM-style Frequency x Monetary basis, and which
-- combined tier (Champions / Loyal / At Risk / Low Value) do they fall into?
-- Note: no transaction date exists in this dataset, so this uses Frequency (previous_purchases)
-- and Monetary (purchase_amount_usd) only -- a true Recency score would need a timestamp column.
WITH scored AS (
    SELECT customer_id,
           previous_purchases,
           purchase_amount_usd,
           NTILE(5) OVER (ORDER BY previous_purchases ASC) AS frequency_score,
           NTILE(5) OVER (ORDER BY purchase_amount_usd ASC) AS monetary_score
    FROM customer_final_data
)
SELECT customer_id,
       frequency_score,
       monetary_score,
       CASE
           WHEN frequency_score >= 4 AND monetary_score >= 4 THEN 'Champions'
           WHEN frequency_score >= 4 AND monetary_score < 4 THEN 'Loyal (Low Spend)'
           WHEN frequency_score < 3 AND monetary_score >= 4 THEN 'At Risk (High Value)'
           ELSE 'Low Value'
       END AS rf_segment
FROM scored
ORDER BY monetary_score DESC, frequency_score DESC;


-- Q13. Does discount usage correlate with lower review ratings?
-- Helps validate (or challenge) the discount-policy recommendation: are discounted
-- purchases actually associated with less satisfied customers?
SELECT discount_applied,
       COUNT(*) AS num_orders,
       ROUND(AVG(review_rating), 2) AS avg_rating,
       ROUND(AVG(purchase_amount_usd), 2) AS avg_spend
FROM customer_final_data
GROUP BY discount_applied;


-- Q14. Which payment methods drive the most revenue, and do they differ in average order value?
-- Common industry use case: prioritizing which payment options to promote or optimize checkout for.
SELECT payment_method,
       COUNT(customer_id) AS total_orders,
       ROUND(SUM(purchase_amount_usd), 2) AS total_revenue,
       ROUND(AVG(purchase_amount_usd), 2) AS avg_order_value
FROM customer_final_data
GROUP BY payment_method
ORDER BY total_revenue DESC;


-- Q15. Within each season, which product category generates the most revenue,
-- and how does it rank against other categories in that season?
-- Useful for seasonal merchandising and marketing-spend allocation decisions.
WITH seasonal_revenue AS (
    SELECT season,
           category,
           SUM(purchase_amount_usd) AS revenue,
           RANK() OVER (PARTITION BY season ORDER BY SUM(purchase_amount_usd) DESC) AS category_rank
    FROM customer_final_data
    GROUP BY season, category
)
SELECT season, category, revenue, category_rank
FROM seasonal_revenue
WHERE category_rank = 1
ORDER BY revenue DESC;
